include_directories(${CMAKE_CURRENT_LIST_DIR}/3rdparty/qwt/src/)

set(XQWT_SOURCES
    ${CMAKE_CURRENT_LIST_DIR}/qwt_abstract_scale_draw.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_clipper.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_color_map.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_column_symbol.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_date.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_date_scale_draw.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_date_scale_engine.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_dyngrid_layout.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_event_pattern.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_graphic.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_interval.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_interval_symbol.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_math.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_magnifier.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_null_paintdevice.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_painter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_painter_command.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_panner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_picker.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_picker_machine.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_pixel_matrix.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_point_3d.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_point_polar.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_round_scale_draw.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_scale_div.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_scale_draw.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_scale_map.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_spline.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_scale_engine.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_symbol.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_system_clock.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_text_engine.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_text_label.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_text.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_transform.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_widget_overlay.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_curve_fitter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_abstract_legend.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_legend.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_legend_data.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_legend_label.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_renderer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_xml.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_axis.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_curve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_dict.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_directpainter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_grid.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_histogram.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_item.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_abstract_barchart.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_barchart.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_multi_barchart.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_intervalcurve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_zoneitem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_tradingcurve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_spectrogram.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_spectrocurve.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_scaleitem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_legenditem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_seriesitem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_shapeitem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_marker.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_textlabel.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_layout.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_canvas.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_panner.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_rasteritem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_picker.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_zoomer.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_magnifier.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_rescaler.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_point_mapper.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_raster_data.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_matrix_raster_data.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_sampling_thread.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_series_data.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_point_data.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_scale_widget.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_glcanvas.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_plot_svgitem.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_abstract_slider.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_abstract_scale.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_arrow_button.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_analog_clock.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_compass.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_compass_rose.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_counter.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_dial.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_dial_needle.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_knob.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_slider.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_thermo.cpp
    ${CMAKE_CURRENT_LIST_DIR}/qwt_wheel.cpp
)
